name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: DnD LaTeX compilation
        uses: matsavage/dnd-latex-action@v0.3.0
        with:
          working_directory: characters
          args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
